### ISSUE TITLE
Add `Sync` version

### ISSUE THREAD

**Issue by XAMPPRocky** [marmeladema/clru-rs#43]
Hey, I was interested in using this crate in one of projects, however I need `CLruCache` to be `Sync`, as I want to share the cache between threads. Would you be willing to either changing to be using `Arc` internally or providing a `sync` version of `CLruCache`?

**Comment by marmeladema** [comment]
Sure! I'll release a new version that will include `Send`. For `Sync`, I would need to review if that's appropriate but I am not sure I am qualified to do so^^ Additionally, most interesting methods are taking a mutable reference to self so how one would use it in a `Sync` context?

**Comment by XAMPPRocky** [comment]
> Additionally, most interesting methods are taking a mutable reference to self so how one would use it in a Sync context?

Through a `Mutex` or `RwLock`? The code I wrote when I tried using this library with `peek` to check the cache with only a read lock and then later a write lock to use `put_with_weight` to insert into the cache, pretty simple.

**Comment by marmeladema** [comment]
I have just tagged version `0.5.0` that should include `Send`.

> Through a Mutex or RwLock? The code I wrote when I tried using this library with peek to check the cache with only a read lock and then later a write lock to use put_with_weight to insert into the cache, pretty simple.

Just to be clear, this is only required for a `RwLock` right?
There is already a test for the `Mutex` case and it works fine: https://github.com/marmeladema/clru-rs/blob/a464acac4594a8159d88df8b6e6ddbece8d6f3b1/src/lib.rs#L2643-L2692

About replacing the `Rc` by an `Arc`, I am worried about the performance impact it might have but I don't have benchmarks to measure it (yet?). I am not against providing a `Sync` version somehow, but I would want to avoid code duplication and macro rules. I'll see what I can do :)
