### ISSUE TITLE
Does the order of elements in FixedSizeList::free matter?

### ISSUE THREAD

**Issue by webmaster128** [marmeladema/clru-rs#8]
If I understand correctly, `FixedSizeList::free` contains a list of position in `FixedSizeList::nodes` that are free to be used. If I also understand correctly, the order in `FixedSizeList::nodes` is irrelevant for the logic, since elements are sorted via the `FixedSizeListNode::prev`/`::next` links.

I wonder because during review I noticed that `free` is filled with elements in descending order in the constructor and in ascending order in `clear`.

Then, isn't `FixedSizeList::free` better modelled as a set, which has no order and elements must be unique?

**Comment by marmeladema** [comment]
Hello and thank you for taking at look at this crate!

I fully agree that semantically, `FixedSizeList::free` is an un-ordered set of free indices.

About `clear`, it should probably keep the same order as the constructor for consistency, even though it's not really required. It's just mostly a mistake on my side.

About modelling `FixedSizeList::free` as a set, what backing storage do you have in mind?

* Using a `HashSet` would introduce more memory allocation and more CPU overhead to access elements than strictly necessary.

* A solution that would be more memory efficient would be to use a bit-set like https://contain-rs.github.io/bit-set/bit_set/ but that would probably also impact performance as it usually requires some bit fiddling operations to convert a basic `usize` into a bit position in the bit-set.

As a side note, I am working on #7 and that might introduce some more assumptions on how that free set is used. Probably that the last element pushed in the free list would be the next one to be popped. Making it a stack in practice.

**Comment by webmaster128** [comment]
Yeah, just found the crate at https://github.com/jeromefroe/lru-rs/issues/93 and really appreciate the almost pointer-free implementation.

I'm more thinking about the semantics than implementation here. I think a doc comment on `free` would do the job as well. I was just trying to understand it, then found the different ways it is filled, was confused, then figured it does not matter.

**Comment by marmeladema** [comment]
A doc comment totally make sense! I will add one shortly :+1:
